/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardSlider".
 */
export type CardSlider =
  | {
      title?: string | null;
      image: number | Media;
      caption?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FactsList".
 */
export type FactsList =
  | {
      factStat: string;
      factDescription: string;
      id?: string | null;
    }[]
  | null;

export interface Config {
  collections: {
    pages: Page;
    posts: Post;
    projects: Project;
    media: Media;
    categories: Category;
    users: User;
    teammates: Teammate;
    listings: Listing;
    testimonials: Testimonial;
    services: Service;
    companies: Company;
    involvementEvents: InvolvementEvent;
    involvementGroups: InvolvementGroup;
    communityResources: CommunityResource;
    redirects: Redirect;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    settings: Settings;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'default' | 'fullscreen' | 'projectHero';
    centeredText: boolean;
    gradient: 'none' | 'red' | 'white';
    headerText?: string | null;
    richText: {
      [k: string]: unknown;
    }[];
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            appearance?: ('default' | 'primary' | 'secondary') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: number | Media | null;
    backupImage?: number | Media | null;
  };
  layout: (
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        invertBackground?: boolean | null;
        columns?:
          | {
              size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
              richText: {
                [k: string]: unknown;
              }[];
              enableLink?: boolean | null;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
                appearance?: ('default' | 'primary' | 'secondary') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        position?: ('default' | 'fullscreen') | null;
        media: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | {
        introContent?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        populateBy?: ('collection' | 'selection') | null;
        relationTo?:
          | (
              | 'posts'
              | 'projects'
              | 'listings'
              | 'teammates'
              | 'involvementGroups'
              | 'involvementEvents'
              | 'testimonials'
              | 'companies'
              | 'services'
              | 'communityResources'
            )
          | null;
        categories?: (number | Category)[] | null;
        limit?: number | null;
        selectedDocs?:
          | (
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }
              | {
                  relationTo: 'projects';
                  value: number | Project;
                }
              | {
                  relationTo: 'listings';
                  value: number | Listing;
                }
              | {
                  relationTo: 'teammates';
                  value: number | Teammate;
                }
              | {
                  relationTo: 'involvementGroups';
                  value: number | InvolvementGroup;
                }
              | {
                  relationTo: 'involvementEvents';
                  value: number | InvolvementEvent;
                }
              | {
                  relationTo: 'testimonials';
                  value: number | Testimonial;
                }
              | {
                  relationTo: 'companies';
                  value: number | Company;
                }
              | {
                  relationTo: 'services';
                  value: number | Service;
                }
              | {
                  relationTo: 'communityResources';
                  value: number | CommunityResource;
                }
            )[]
          | null;
        populatedDocs?:
          | (
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }
              | {
                  relationTo: 'projects';
                  value: number | Project;
                }
              | {
                  relationTo: 'listings';
                  value: number | Listing;
                }
              | {
                  relationTo: 'teammates';
                  value: number | Teammate;
                }
              | {
                  relationTo: 'involvementGroups';
                  value: number | InvolvementGroup;
                }
              | {
                  relationTo: 'involvementEvents';
                  value: number | InvolvementEvent;
                }
              | {
                  relationTo: 'testimonials';
                  value: number | Testimonial;
                }
              | {
                  relationTo: 'companies';
                  value: number | Company;
                }
              | {
                  relationTo: 'services';
                  value: number | Service;
                }
              | {
                  relationTo: 'communityResources';
                  value: number | CommunityResource;
                }
            )[]
          | null;
        populatedDocsTotal?: number | null;
        bgColor?: ('default' | 'red') | null;
        displayHeader?: ('yes' | 'no') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'archive';
      }
    | {
        title: string;
        subheadingType?: ('none' | 'text' | 'location') | null;
        subheading?: string | null;
        description: string;
        position?: ('left' | 'right') | null;
        bgColor?: ('white' | 'red') | null;
        facts?: FactsList;
        media: number | Media;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
                appearance?: ('default' | 'primary' | 'secondary') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectBlock';
      }
    | {
        title: string;
        description?: string | null;
        facts?: FactsList;
        youtubeLink: string;
        youtubeThumbnail: number | Media;
        bgImage?: number | Media | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsAndVideoBlock';
      }
    | {
        title: string;
        richText: {
          [k: string]: unknown;
        }[];
        facts?: FactsList;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentAndStatsBlock';
      }
    | {
        title?: string | null;
        description?: string | null;
        facts?: FactsList;
        bgColor?: ('white' | 'red') | null;
        bgImage?: number | Media | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statBlock';
      }
    | {
        locations?: (number | Project)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'googleMapsBlock';
      }
    | {
        title?: string | null;
        description?: string | null;
        youtubeLink: string;
        youtubeThumbnail: number | Media;
        bgImage?: number | Media | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videoBlock';
      }
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: number | Media | null;
  };
  slug?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title?: string | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'default' | 'fullscreen' | 'projectHero';
    centeredText: boolean;
    gradient: 'none' | 'red' | 'white';
    headerText?: string | null;
    richText: {
      [k: string]: unknown;
    }[];
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            appearance?: ('default' | 'primary' | 'secondary') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: number | Media | null;
    backupImage?: number | Media | null;
  };
  layout: (
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        invertBackground?: boolean | null;
        columns?:
          | {
              size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
              richText: {
                [k: string]: unknown;
              }[];
              enableLink?: boolean | null;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
                appearance?: ('default' | 'primary' | 'secondary') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        position?: ('default' | 'fullscreen') | null;
        media: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | {
        introContent?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        populateBy?: ('collection' | 'selection') | null;
        relationTo?:
          | (
              | 'posts'
              | 'projects'
              | 'listings'
              | 'teammates'
              | 'involvementGroups'
              | 'involvementEvents'
              | 'testimonials'
              | 'companies'
              | 'services'
              | 'communityResources'
            )
          | null;
        categories?: (number | Category)[] | null;
        limit?: number | null;
        selectedDocs?:
          | (
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }
              | {
                  relationTo: 'projects';
                  value: number | Project;
                }
              | {
                  relationTo: 'listings';
                  value: number | Listing;
                }
              | {
                  relationTo: 'teammates';
                  value: number | Teammate;
                }
              | {
                  relationTo: 'involvementGroups';
                  value: number | InvolvementGroup;
                }
              | {
                  relationTo: 'involvementEvents';
                  value: number | InvolvementEvent;
                }
              | {
                  relationTo: 'testimonials';
                  value: number | Testimonial;
                }
              | {
                  relationTo: 'companies';
                  value: number | Company;
                }
              | {
                  relationTo: 'services';
                  value: number | Service;
                }
              | {
                  relationTo: 'communityResources';
                  value: number | CommunityResource;
                }
            )[]
          | null;
        populatedDocs?:
          | (
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }
              | {
                  relationTo: 'projects';
                  value: number | Project;
                }
              | {
                  relationTo: 'listings';
                  value: number | Listing;
                }
              | {
                  relationTo: 'teammates';
                  value: number | Teammate;
                }
              | {
                  relationTo: 'involvementGroups';
                  value: number | InvolvementGroup;
                }
              | {
                  relationTo: 'involvementEvents';
                  value: number | InvolvementEvent;
                }
              | {
                  relationTo: 'testimonials';
                  value: number | Testimonial;
                }
              | {
                  relationTo: 'companies';
                  value: number | Company;
                }
              | {
                  relationTo: 'services';
                  value: number | Service;
                }
              | {
                  relationTo: 'communityResources';
                  value: number | CommunityResource;
                }
            )[]
          | null;
        populatedDocsTotal?: number | null;
        bgColor?: ('default' | 'red') | null;
        displayHeader?: ('yes' | 'no') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'archive';
      }
  )[];
  enablePremiumContent?: boolean | null;
  premiumContent?:
    | (
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            invertBackground?: boolean | null;
            columns?:
              | {
                  size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
                  richText: {
                    [k: string]: unknown;
                  }[];
                  enableLink?: boolean | null;
                  link?: {
                    type?: ('reference' | 'custom') | null;
                    newTab?: boolean | null;
                    reference?: {
                      relationTo: 'pages';
                      value: number | Page;
                    } | null;
                    url?: string | null;
                    label: string;
                    appearance?: ('default' | 'primary' | 'secondary') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            position?: ('default' | 'fullscreen') | null;
            media: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            introContent?:
              | {
                  [k: string]: unknown;
                }[]
              | null;
            populateBy?: ('collection' | 'selection') | null;
            relationTo?:
              | (
                  | 'posts'
                  | 'projects'
                  | 'listings'
                  | 'teammates'
                  | 'involvementGroups'
                  | 'involvementEvents'
                  | 'testimonials'
                  | 'companies'
                  | 'services'
                  | 'communityResources'
                )
              | null;
            categories?: (number | Category)[] | null;
            limit?: number | null;
            selectedDocs?:
              | (
                  | {
                      relationTo: 'posts';
                      value: number | Post;
                    }
                  | {
                      relationTo: 'projects';
                      value: number | Project;
                    }
                  | {
                      relationTo: 'listings';
                      value: number | Listing;
                    }
                  | {
                      relationTo: 'teammates';
                      value: number | Teammate;
                    }
                  | {
                      relationTo: 'involvementGroups';
                      value: number | InvolvementGroup;
                    }
                  | {
                      relationTo: 'involvementEvents';
                      value: number | InvolvementEvent;
                    }
                  | {
                      relationTo: 'testimonials';
                      value: number | Testimonial;
                    }
                  | {
                      relationTo: 'companies';
                      value: number | Company;
                    }
                  | {
                      relationTo: 'services';
                      value: number | Service;
                    }
                  | {
                      relationTo: 'communityResources';
                      value: number | CommunityResource;
                    }
                )[]
              | null;
            populatedDocs?:
              | (
                  | {
                      relationTo: 'posts';
                      value: number | Post;
                    }
                  | {
                      relationTo: 'projects';
                      value: number | Project;
                    }
                  | {
                      relationTo: 'listings';
                      value: number | Listing;
                    }
                  | {
                      relationTo: 'teammates';
                      value: number | Teammate;
                    }
                  | {
                      relationTo: 'involvementGroups';
                      value: number | InvolvementGroup;
                    }
                  | {
                      relationTo: 'involvementEvents';
                      value: number | InvolvementEvent;
                    }
                  | {
                      relationTo: 'testimonials';
                      value: number | Testimonial;
                    }
                  | {
                      relationTo: 'companies';
                      value: number | Company;
                    }
                  | {
                      relationTo: 'services';
                      value: number | Service;
                    }
                  | {
                      relationTo: 'communityResources';
                      value: number | CommunityResource;
                    }
                )[]
              | null;
            populatedDocsTotal?: number | null;
            bgColor?: ('default' | 'red') | null;
            displayHeader?: ('yes' | 'no') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'archive';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: number | Media | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  relatedPosts?: (number | Post)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  address: string;
  description: string;
  neighborhood?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  price?: string | null;
  agents?: (number | Teammate)[] | null;
  slider?: CardSlider;
  website?: string | null;
  instagram?: string | null;
  layout: (
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        invertBackground?: boolean | null;
        columns?:
          | {
              size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
              richText: {
                [k: string]: unknown;
              }[];
              enableLink?: boolean | null;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
                appearance?: ('default' | 'primary' | 'secondary') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        title: string;
        richText: {
          [k: string]: unknown;
        }[];
        facts?: FactsList;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentAndStatsBlock';
      }
    | {
        position?: ('default' | 'fullscreen') | null;
        media: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | {
        introContent?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        populateBy?: ('collection' | 'selection') | null;
        relationTo?:
          | (
              | 'posts'
              | 'projects'
              | 'listings'
              | 'teammates'
              | 'involvementGroups'
              | 'involvementEvents'
              | 'testimonials'
              | 'companies'
              | 'services'
              | 'communityResources'
            )
          | null;
        categories?: (number | Category)[] | null;
        limit?: number | null;
        selectedDocs?:
          | (
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }
              | {
                  relationTo: 'projects';
                  value: number | Project;
                }
              | {
                  relationTo: 'listings';
                  value: number | Listing;
                }
              | {
                  relationTo: 'teammates';
                  value: number | Teammate;
                }
              | {
                  relationTo: 'involvementGroups';
                  value: number | InvolvementGroup;
                }
              | {
                  relationTo: 'involvementEvents';
                  value: number | InvolvementEvent;
                }
              | {
                  relationTo: 'testimonials';
                  value: number | Testimonial;
                }
              | {
                  relationTo: 'companies';
                  value: number | Company;
                }
              | {
                  relationTo: 'services';
                  value: number | Service;
                }
              | {
                  relationTo: 'communityResources';
                  value: number | CommunityResource;
                }
            )[]
          | null;
        populatedDocs?:
          | (
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }
              | {
                  relationTo: 'projects';
                  value: number | Project;
                }
              | {
                  relationTo: 'listings';
                  value: number | Listing;
                }
              | {
                  relationTo: 'teammates';
                  value: number | Teammate;
                }
              | {
                  relationTo: 'involvementGroups';
                  value: number | InvolvementGroup;
                }
              | {
                  relationTo: 'involvementEvents';
                  value: number | InvolvementEvent;
                }
              | {
                  relationTo: 'testimonials';
                  value: number | Testimonial;
                }
              | {
                  relationTo: 'companies';
                  value: number | Company;
                }
              | {
                  relationTo: 'services';
                  value: number | Service;
                }
              | {
                  relationTo: 'communityResources';
                  value: number | CommunityResource;
                }
            )[]
          | null;
        populatedDocsTotal?: number | null;
        bgColor?: ('default' | 'red') | null;
        displayHeader?: ('yes' | 'no') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'archive';
      }
    | {
        title: string;
        subheadingType?: ('none' | 'text' | 'location') | null;
        subheading?: string | null;
        description: string;
        position?: ('left' | 'right') | null;
        bgColor?: ('white' | 'red') | null;
        facts?: FactsList;
        media: number | Media;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
                appearance?: ('default' | 'primary' | 'secondary') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectBlock';
      }
    | {
        title: string;
        description?: string | null;
        facts?: FactsList;
        youtubeLink: string;
        youtubeThumbnail: number | Media;
        bgImage?: number | Media | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsAndVideoBlock';
      }
    | {
        title?: string | null;
        description?: string | null;
        facts?: FactsList;
        bgColor?: ('white' | 'red') | null;
        bgImage?: number | Media | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statBlock';
      }
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: number | Media | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  relatedProjects?: (number | Project)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teammates".
 */
export interface Teammate {
  id: number;
  title: string;
  profilePic: number | Media;
  jobTitle: string;
  profileIntroduction: string;
  bio: string;
  strengths: string;
  yearsOfExperience: number;
  rank: number;
  favoritePlaces?: (number | CommunityResource)[] | null;
  phoneNumber: string;
  officeNumber?: string | null;
  email: string;
  instagram?: string | null;
  Facebook?: string | null;
  Linkedin?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: number | Media | null;
  };
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communityResources".
 */
export interface CommunityResource {
  id: number;
  title: string;
  address: string;
  description: string;
  categories: number | Category;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  title: string;
  address: string;
  listingType?: ('forSale' | 'lease' | 'forSaleLease') | null;
  streetAddress: string;
  neighborhood?: string | null;
  city: string;
  zipCode: string;
  county: string;
  state: string;
  latitude: number;
  longitude: number;
  isPriceNegotiable: boolean;
  price?: number | null;
  paymentFrequency?: ('oneTime' | 'dollarPerSqPerYear' | 'monthly' | 'yearly') | null;
  agents?: (number | Teammate)[] | null;
  listingFlyer?: number | Media | null;
  zillowLink?: string | null;
  virtualTourLink?: string | null;
  coverImage: number | Media;
  imageGallery?:
    | {
        image?: number | Media | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  propertyTypes?:
    | (
        | 'singleFamily'
        | 'multiFamily'
        | 'townhouse'
        | 'condo'
        | 'co-op'
        | 'apt'
        | 'mobileHome'
        | 'vacationHome'
        | 'seniorLivingHome'
        | 'shoppingCenter'
        | 'bizOpportunity'
        | 'office'
        | 'retail'
        | 'industrial'
        | 'mixedUse'
        | 'hotel'
        | 'motel'
        | 'restaurant'
        | 'healthcareFacility'
        | 'storageUnit'
        | 'vacantLand'
        | 'agriculturalLand'
        | 'timberland'
        | 'ranchLand'
        | 'recreationalLand'
        | 'developmentLand'
        | 'religion'
        | 'school'
        | 'university'
        | 'governmentBuilding'
        | 'cemetery'
        | 'airport'
        | 'utility'
        | 'reit'
        | 'rentalProperty'
        | 'fixAndFlip'
      )
    | null;
  propertySubtype?: string | null;
  sqFt?: number | null;
  sqFtLand?: number | null;
  sqFtLot?: number | null;
  bedCount?: number | null;
  bathroomCount?: number | null;
  overview: string;
  areaOverview?: string | null;
  fullDescription?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  zoningType?: ('C' | 'r' | 'i') | null;
  buildingClass?: ('A' | 'B' | 'C') | null;
  tenancyType?: ('Single Tenant' | 'Multi-Tenant') | null;
  yearBuilt?: number | null;
  yearRenovated?: number | null;
  occupancy?: number | null;
  highlights?:
    | {
        highlightText?: string | null;
        id?: string | null;
      }[]
    | null;
  heat?: ('n/a' | 'yes' | 'no') | null;
  cool?: ('n/a' | 'yes' | 'no') | null;
  electricity?: ('n/a' | 'yes' | 'no') | null;
  water?: ('n/a' | 'yes' | 'no') | null;
  waste?: ('n/a' | 'yes' | 'no') | null;
  sewer?: ('n/a' | 'yes' | 'no') | null;
  internet?: ('n/a' | 'yes' | 'no') | null;
  lighting?: ('n/a' | 'yes' | 'no') | null;
  hasParking?: boolean | null;
  parkingDescription?: string | null;
  layout: (
    | {
        invertBackground?: boolean | null;
        columns?:
          | {
              size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
              richText: {
                [k: string]: unknown;
              }[];
              enableLink?: boolean | null;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
                appearance?: ('default' | 'primary' | 'secondary') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        position?: ('default' | 'fullscreen') | null;
        media: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | {
        introContent?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        populateBy?: ('collection' | 'selection') | null;
        relationTo?:
          | (
              | 'posts'
              | 'projects'
              | 'listings'
              | 'teammates'
              | 'involvementGroups'
              | 'involvementEvents'
              | 'testimonials'
              | 'companies'
              | 'services'
              | 'communityResources'
            )
          | null;
        categories?: (number | Category)[] | null;
        limit?: number | null;
        selectedDocs?:
          | (
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }
              | {
                  relationTo: 'projects';
                  value: number | Project;
                }
              | {
                  relationTo: 'listings';
                  value: number | Listing;
                }
              | {
                  relationTo: 'teammates';
                  value: number | Teammate;
                }
              | {
                  relationTo: 'involvementGroups';
                  value: number | InvolvementGroup;
                }
              | {
                  relationTo: 'involvementEvents';
                  value: number | InvolvementEvent;
                }
              | {
                  relationTo: 'testimonials';
                  value: number | Testimonial;
                }
              | {
                  relationTo: 'companies';
                  value: number | Company;
                }
              | {
                  relationTo: 'services';
                  value: number | Service;
                }
              | {
                  relationTo: 'communityResources';
                  value: number | CommunityResource;
                }
            )[]
          | null;
        populatedDocs?:
          | (
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }
              | {
                  relationTo: 'projects';
                  value: number | Project;
                }
              | {
                  relationTo: 'listings';
                  value: number | Listing;
                }
              | {
                  relationTo: 'teammates';
                  value: number | Teammate;
                }
              | {
                  relationTo: 'involvementGroups';
                  value: number | InvolvementGroup;
                }
              | {
                  relationTo: 'involvementEvents';
                  value: number | InvolvementEvent;
                }
              | {
                  relationTo: 'testimonials';
                  value: number | Testimonial;
                }
              | {
                  relationTo: 'companies';
                  value: number | Company;
                }
              | {
                  relationTo: 'services';
                  value: number | Service;
                }
              | {
                  relationTo: 'communityResources';
                  value: number | CommunityResource;
                }
            )[]
          | null;
        populatedDocsTotal?: number | null;
        bgColor?: ('default' | 'red') | null;
        displayHeader?: ('yes' | 'no') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'archive';
      }
    | {
        title: string;
        subheadingType?: ('none' | 'text' | 'location') | null;
        subheading?: string | null;
        description: string;
        position?: ('left' | 'right') | null;
        bgColor?: ('white' | 'red') | null;
        facts?: FactsList;
        media: number | Media;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
                appearance?: ('default' | 'primary' | 'secondary') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectBlock';
      }
    | {
        title: string;
        description?: string | null;
        facts?: FactsList;
        youtubeLink: string;
        youtubeThumbnail: number | Media;
        bgImage?: number | Media | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsAndVideoBlock';
      }
    | {
        title?: string | null;
        description?: string | null;
        facts?: FactsList;
        bgColor?: ('white' | 'red') | null;
        bgImage?: number | Media | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statBlock';
      }
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: number | Media | null;
  };
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "involvementGroups".
 */
export interface InvolvementGroup {
  id: number;
  title: string;
  highlight: string;
  description: string;
  image: number | Media;
  linkToGroupWebsite?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "involvementEvents".
 */
export interface InvolvementEvent {
  id: number;
  title: string;
  description?: string | null;
  image: number | Media;
  eventDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  title: string;
  quote: string;
  image: number | Media;
  jobTitle: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  shortDescription?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'default' | 'fullscreen' | 'projectHero';
    centeredText: boolean;
    gradient: 'none' | 'red' | 'white';
    headerText?: string | null;
    richText: {
      [k: string]: unknown;
    }[];
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            appearance?: ('default' | 'primary' | 'secondary') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: number | Media | null;
    backupImage?: number | Media | null;
  };
  layout: (
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        invertBackground?: boolean | null;
        columns?:
          | {
              size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
              richText: {
                [k: string]: unknown;
              }[];
              enableLink?: boolean | null;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
                appearance?: ('default' | 'primary' | 'secondary') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        position?: ('default' | 'fullscreen') | null;
        media: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | {
        introContent?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        populateBy?: ('collection' | 'selection') | null;
        relationTo?:
          | (
              | 'posts'
              | 'projects'
              | 'listings'
              | 'teammates'
              | 'involvementGroups'
              | 'involvementEvents'
              | 'testimonials'
              | 'companies'
              | 'services'
              | 'communityResources'
            )
          | null;
        categories?: (number | Category)[] | null;
        limit?: number | null;
        selectedDocs?:
          | (
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }
              | {
                  relationTo: 'projects';
                  value: number | Project;
                }
              | {
                  relationTo: 'listings';
                  value: number | Listing;
                }
              | {
                  relationTo: 'teammates';
                  value: number | Teammate;
                }
              | {
                  relationTo: 'involvementGroups';
                  value: number | InvolvementGroup;
                }
              | {
                  relationTo: 'involvementEvents';
                  value: number | InvolvementEvent;
                }
              | {
                  relationTo: 'testimonials';
                  value: number | Testimonial;
                }
              | {
                  relationTo: 'companies';
                  value: number | Company;
                }
              | {
                  relationTo: 'services';
                  value: number | Service;
                }
              | {
                  relationTo: 'communityResources';
                  value: number | CommunityResource;
                }
            )[]
          | null;
        populatedDocs?:
          | (
              | {
                  relationTo: 'posts';
                  value: number | Post;
                }
              | {
                  relationTo: 'projects';
                  value: number | Project;
                }
              | {
                  relationTo: 'listings';
                  value: number | Listing;
                }
              | {
                  relationTo: 'teammates';
                  value: number | Teammate;
                }
              | {
                  relationTo: 'involvementGroups';
                  value: number | InvolvementGroup;
                }
              | {
                  relationTo: 'involvementEvents';
                  value: number | InvolvementEvent;
                }
              | {
                  relationTo: 'testimonials';
                  value: number | Testimonial;
                }
              | {
                  relationTo: 'companies';
                  value: number | Company;
                }
              | {
                  relationTo: 'services';
                  value: number | Service;
                }
              | {
                  relationTo: 'communityResources';
                  value: number | CommunityResource;
                }
            )[]
          | null;
        populatedDocsTotal?: number | null;
        bgColor?: ('default' | 'red') | null;
        displayHeader?: ('yes' | 'no') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'archive';
      }
    | {
        title: string;
        subheadingType?: ('none' | 'text' | 'location') | null;
        subheading?: string | null;
        description: string;
        position?: ('left' | 'right') | null;
        bgColor?: ('white' | 'red') | null;
        facts?: FactsList;
        media: number | Media;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
                appearance?: ('default' | 'primary' | 'secondary') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectBlock';
      }
    | {
        title: string;
        description?: string | null;
        facts?: FactsList;
        youtubeLink: string;
        youtubeThumbnail: number | Media;
        bgImage?: number | Media | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsAndVideoBlock';
      }
    | {
        title?: string | null;
        description?: string | null;
        facts?: FactsList;
        bgColor?: ('white' | 'red') | null;
        bgImage?: number | Media | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statBlock';
      }
    | {
        title: string;
        richText: {
          [k: string]: unknown;
        }[];
        facts?: FactsList;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentAndStatsBlock';
      }
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: number | Media | null;
  };
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'user')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Settings {
  id: number;
  postsPage?: (number | null) | Page;
  projectsPage?: (number | null) | Page;
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}